---
title: "Preliminary Results Part Code"
format: html
editor: visual
---

```{r}
library(ggplot2)

filtered_data <- subset(realtor_data_zip, state == "Puerto Rico")
filtered_data <- na.omit(filtered_data)

filtered_data$zip_code <- as.factor(filtered_data$zip_code)

str(filtered_data)
summary(filtered_data)
nrow(filtered_data) 
```

```{r}
ggplot(realtor_data_zip, aes(x = log(price))) +
  geom_histogram(binwidth = 0.3, fill = "darkorange", color = "white") +
  labs(
    title = "Log-Transformed Distribution of Housing Prices",
    x = "log(Price)",
    y = "Count"
  ) +
  theme_minimal()

summary(real_estate_data$price)
```

```{r}
model <- lm(price ~ bed + bath + house_size + acre_lot + zip_code, data = filtered_data)

summary(model)
```

```{r}
ggplot(data = data.frame(fitted = fitted(model), residuals = residuals(model)), 
       aes(x = fitted, y = residuals)) +
  geom_point(alpha = 0.5, color = "purple") +
  geom_hline(yintercept = 0, color = "pink4", linetype = "dashed") +
  labs(title = "Residuals vs Fitted Values", x = "Fitted Values", y = "Residuals")

```

```{r}
ggplot(data = data.frame(residuals = residuals(model)), aes(x = residuals)) +
  geom_histogram(fill = "lightblue", color = "black", bins = 30) +
  labs(title = "Histogram of Residuals", x = "Residuals", y = "Frequency")

```

```{r}
qqnorm(residuals(model), main = "Q-Q Plot of Residuals")
qqline(residuals(model), col="purple", lwd=2)

```
